# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: divyum
  pool: 5
  username: divyum
  password:

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: divyum
  pool: 5
  username: divyum
  password:

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: divyum
  pool: 5
  username: divyum
  password:
